{
 "title": "Jenkins: Jobs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of Jenkins Masters",
   "type": "graph",
   "description": "# of Jenkins masters currently running in the cluster",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(jenkinsstatsd_mesos_cloud_mesos_provision_mesos_samples)"
    }
   ]
  },
  {
   "title": "Success Rate [1m] (total)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "runs/second" }
   ],
   "targets": [
    {
     "expr": "sum(jenkinsstatsd_jenkins_runs_success_m1_rate)"
    }
   ]
  },
  {
   "title": "Queue Size (total)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jenkinsstatsd_jenkins_queue_size_value)"
    }
   ]
  },
  {
   "title": "Success Rate [1m]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkinsstatsd_jenkins_runs_success_m1_rate",
     "legendFormat": "{{dcos_service_name}}"
    }
   ]
  },
  {
   "title": "Failure Rate [1m] (total)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "runs/second" }
   ],
   "targets": [
    {
     "expr": "sum(jenkinsstatsd_jenkins_runs_failure_m1_rate)"
    }
   ]
  },
  {
   "title": "Executors Free (total)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Executors" }
   ],
   "targets": [
    {
     "expr": "sum(jenkinsstatsd_jenkins_executor_free_value)"
    }
   ]
  },
  {
   "title": "Failure Rate [1m]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkinsstatsd_jenkins_runs_failure_m1_rate",
     "legendFormat": "{{dcos_service_name}}"
    }
   ]
  },
  {
   "title": "Build Rate (total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jenkinsstatsd_jenkins_runs_total_m1_rate)"
    }
   ]
  },
  {
   "title": "Executors Total (total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Executors" }
   ],
   "targets": [
    {
     "expr": "sum(jenkinsstatsd_jenkins_executor_count_value)"
    }
   ]
  },
  {
   "title": "Build Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkinsstatsd_jenkins_runs_total_m1_rate"
    }
   ]
  },
  {
   "title": "Job Waiting Duration (median)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkinsstatsd_jenkins_job_waiting_duration_mean",
     "legendFormat": "{{dcos_service_name}}"
    }
   ]
  }
 ]
}